steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
  id: Pushing the image to registry
- name: 'kevinsimper/render'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      /render -f /workspace/kubernetes/deployment.yml -var sha=$COMMIT_SHA -o /workspace
      cat /workspace/workspace/kubernetes/deployment.yml
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '/workspace/workspace/kubernetes/deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=staging'
