steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nodejs-cloudbuild-kubernetes/nodejs-cloudbuild-kubernetes:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nodejs-cloudbuild-kubernetes/nodejs-cloudbuild-kubernetes:$COMMIT_SHA']
- name: 'kevinsimper/render'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      /render -f /workspace/kubernetes/deployment.yml -var sha=$COMMIT_SHA -o /workspace
      cat /workspace/workspace/kubernetes/deployment.yml
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '/workspace/workspace/kubernetes/deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=staging'
